/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Addresses;
import jooq.tables.Users;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.USERS</code>.
     */
    public static final Users USERS = jooq.tables.Users.USERS;

    /**
     * The table <code>PUBLIC.ADDRESSES</code>.
     */
    public static final Addresses ADDRESSES = jooq.tables.Addresses.ADDRESSES;
}
